### ISSUE TITLE
[Bug] No buff icons

### ISSUE THREAD

**Issue by Rellegeight** [Aelto/tw3-crow#1]
All tweaks seem to be working, but no stamina regeneration buff icons are shown.

Running mod v3.1 on game v4.03.

`Display Current Buffs` is toggled **ON**.
I have tried the `crowfix` command.

https://github.com/Aelto/tw3-crow/assets/137833586/30a01b9f-6422-4486-8b9d-a7becfeb3f73

**Comment by Aelto** [comment]
CROW doesn't show an icon anymore, instead if you've merged and included all CROW code in the resulting merges it will temporarily use the XP bar to display how much % of stamina you gain per second. As soon as you leave combat it goes back t displaying experience normally

**Comment by Rellegeight** [comment]
Oh, thanks, I see now. Using the XP bar for visualization is far cleaner :).

**Comment by Aelto** [comment]
It is indeed! Compared to the buff counter at least now you instantly know how much you gain per second. I'm marking this as closed
