### ISSUE TITLE
4.04 compatibility

### ISSUE THREAD

**Issue by m4st3rP** [Aelto/tw3-crow#2]
When I launch this mod under 4.04 the script compilation fails with the following log:

> Error [modbrothersinarms]game\player\playerwitcher.ws(11781): Could not find function 'SetRadialPotionUpperTimer'
> Error [modbrothersinarms]game\player\playerwitcher.ws(11787): Could not find function 'SetRadialPotionLowerTimer'
> 
> Warning [content0]engine\environment.ws(30): Global native function 'EnableDebugOverlayFilter' was not exported from C++ code.
> Warning [content0]engine\environment.ws(32): Global native function 'EnableDebugPostProcess' was not exported from C++ code.
> Warning [content0]engine\showflags.ws(11): Global native function 'DebugSetEShowFlag' was not exported from C++ code.

**Comment by m4st3rP** [comment]
It seems to work when the shared util modules are updated. At least the game starts and loads now.

**Comment by Aelto** [comment]
Yes sorry for the delay, I'm away from home at the moment. The mod needs an update, or at least its sharedutils. I'm working on an update and a few design changes around parries and the ability to block and I prefer to make sure the design is on point!
